base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"       # name app

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.single_course, name='single_course'),
]

shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(max_length=255)
    create_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    student_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    create_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.title

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from . import models


def index(request):
    cousers = models.Course.objects.all()
    # return HttpResponse("".join([str(corser) + "<br>" for corser in cousers]))
    return render(request, 'shop/courser.html', context={'cousers': cousers})


def single_course(request, course_id):
 #   # option 1 404
 #   try:
 #       course = models.Course.objects.get(pk=course_id)
 #       return render(request, 'shop/single_course.html', {'course': course})
 #   except models.Course.DoesNotExist:
 #       raise Http404

    # option 2  404
    course = get_object_or_404(models.Course, pk=course_id)
    return render(request, 'shop/single_course.html', {'course': course})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> 
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href="{% url "shop:index" %}" class="navbar-brand">Courses Shop</a>
        </div>
    </nav>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/shop/courser.html
{% extends "base.html" %}

{% block title%}All courses{%endblock title%}

{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Student Quantity</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for cours in cousers %}
        <tr>
            <td>
            <!--<a href={{ cours.id}}>{{cours.title}}</a> -->
            <!--<a href="/shop/{{ cours.id}}">{{cours.title}}</a> -->
            <!-- <a href={\% url "single_course" cours.id %\}>{{cours.title}}</a>      <!-- # url-url.py  "single_course"-name_path  cours.id-argument -->
            <a href={% url "shop:single_course" cours.id %}>{{cours.title}}</a>      <!-- # url-url.py  "single_course"-name_path  cours.id-argument -->
            </td>
            <td>{{cours.category}}</td>
            <td>{{cours.price}}</td>
            <td>{{cours.student_qty}}</td>
            <td><button class="btn btn-primary">Buy</button></td>
        </tr>
        {% endfor %} 
    </tbody>
</table>
{% endblock  %}

templates/shop/single_course.html
{% extends "base.html" %}

{% block title %} {{course.title}} {% endblock %}

{% block content %}
    <h1 class='mt-5'>Title: {{course.title}}</h1>
    <h2>Category: {{course.category}}</h2>
    <p>Price: {{course.price}}</p>
    <p>Student Quantity: {{course.student_qty}}</p>
    <p>Reviews Quantity: {{course.reviews_qty}}</p>
    <p>Create at: {{course.create_at}}</p>
    <p><button class="btn btn-primary">Buy</button></td>
{% endblock  %}